[package]
name = "modern-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-service = "0.3.2"
tower-layer = "0.3.2"
axum-core = { version = "0.4.3" }
axum = { version = "0.7.4", default-features = false, features = ["multipart"] }
async-trait = { version = "0.1.77" }