[package]
name = "modern-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-service = "0.3.2"
tower-layer = "0.3.2"
serde = { version = "1.0.196", default-features = false, features = ["derive"] }